name: Go

on:
  pull_request:
    branches: [ "*" ]

jobs:

  golang-actions:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ">=1.20.0"

    - name: Test
      run: go test -v ./...
